name: interesting_places
description: a
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  drift: ^2.12.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  intl: any
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  drift_dev: ^2.12.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto-Regular.ttf
